# Tobigs 21기 4주차 정규세션 Ensemble

### 앙상블 모델 최소 2가지를 이용해 코드를 짜주세요!
- 전처리와 모델 성능결과 출력 모두 진행해주세요.
- 데이터셋: https://www.kaggle.com/datasets/sakshigoyal7/credit-card-customers
    - 다른 데이터셋을 사용해도 괜찮습니다! 대신 출처를 명시해주세요.

In [12]:
import numpy as np
import pandas as pd

df= pd.read_csv('BankChurners.csv')

In [13]:
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import classification_report, accuracy_score

In [16]:
# 타겟 변수를 0, 1로 변환
df['Attrition_Flag'] = df['Attrition_Flag'].apply(lambda x: 1 if x == 'Attrited Customer' else 0)

In [17]:
# 범주형 변수를 원-핫 인코딩
df = pd.get_dummies(df)

In [18]:
# 트레인/테스트 셋 분리
X = df.drop('Attrition_Flag', axis=1)
y = df['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# 랜덤 포레스트 모델 학습
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# 그래디언트 부스팅 모델 학습
gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)

# 랜덤 포레스트 모델 예측 및 성능 평가
rf_pred = rf.predict(X_test)
print('Random Forest Performance:')
print(classification_report(y_test, rf_pred))
print('Accuracy:', accuracy_score(y_test, rf_pred))

# 그래디언트 부스팅 모델 예측 및 성능 평가
gb_pred = gb.predict(X_test)
print('\nGradient Boosting Performance:')
print(classification_report(y_test, gb_pred))
print('Accuracy:', accuracy_score(y_test, gb_pred))

Random Forest Performance:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1699
           1       1.00      1.00      1.00       327

    accuracy                           1.00      2026
   macro avg       1.00      1.00      1.00      2026
weighted avg       1.00      1.00      1.00      2026

Accuracy: 1.0

Gradient Boosting Performance:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1699
           1       1.00      1.00      1.00       327

    accuracy                           1.00      2026
   macro avg       1.00      1.00      1.00      2026
weighted avg       1.00      1.00      1.00      2026

Accuracy: 1.0